"""init

Revision ID: 38e66fd59fad
Revises: 
Create Date: 2024-09-25 16:39:59.667849

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "38e66fd59fad"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_datas", "shop_coins")
    op.drop_column("user_datas", "align")
    op.drop_column("user_datas", "attempts")
    op.drop_column("user_datas", "clan")
    op.drop_column("user_datas", "count_refs")
    op.drop_column("user_datas", "user_from")
    op.drop_column("user_datas", "dice")
    op.drop_column("user_datas", "rating_all")
    op.drop_column("user_datas", "rating_month")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_datas",
        sa.Column("rating_month", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "user_datas",
        sa.Column("rating_all", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "user_datas",
        sa.Column("dice", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "user_datas",
        sa.Column("user_from", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "user_datas",
        sa.Column("count_refs", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "user_datas",
        sa.Column("clan", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "user_datas",
        sa.Column("attempts", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "user_datas",
        sa.Column("align", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "user_datas",
        sa.Column("shop_coins", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
